-- CreateEnum
CREATE TYPE "ContractEndReason" AS ENUM ('CHECKOUT', 'TRANSFER', 'RENEWAL', 'CANCELLED');

-- ============================================================
-- SECTION 1: Contracts — end reason, renewal/transfer chain, deposit settlement
-- ============================================================
ALTER TABLE "contracts"
    ADD COLUMN "endReason" "ContractEndReason",
    ADD COLUMN "previousContractId" TEXT,
    ADD COLUMN "depositDeduction" DECIMAL(12,2),
    ADD COLUMN "depositRefunded" DECIMAL(12,2),
    ADD COLUMN "depositNote" TEXT;

CREATE UNIQUE INDEX "contracts_previousContractId_key" ON "contracts"("previousContractId");

ALTER TABLE "contracts" ADD CONSTRAINT "contracts_previousContractId_fkey"
    FOREIGN KEY ("previousContractId") REFERENCES "contracts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================
-- SECTION 2: Payments — bill by billing period, not calendar month alone
-- ============================================================
ALTER TABLE "payments"
    ADD COLUMN "periodStart" TIMESTAMP(3),
    ADD COLUMN "periodEnd" TIMESTAMP(3);

-- Backfill: every existing payment was generated by the old monthly-only
-- generator, so its period is exactly the calendar month it was billed for.
UPDATE "payments"
SET
    "periodStart" = make_date("periodYear", "periodMonth", 1)::timestamp,
    "periodEnd" = (make_date("periodYear", "periodMonth", 1) + INTERVAL '1 month')::timestamp
WHERE "periodStart" IS NULL;

ALTER TABLE "payments"
    ALTER COLUMN "periodStart" SET NOT NULL,
    ALTER COLUMN "periodEnd" SET NOT NULL;

DROP INDEX IF EXISTS "payments_contractId_periodMonth_periodYear_key";

CREATE UNIQUE INDEX "payments_contractId_periodStart_key" ON "payments"("contractId", "periodStart");
CREATE INDEX "payments_periodYear_periodMonth_idx" ON "payments"("periodYear", "periodMonth");
CREATE INDEX "payments_dueDate_idx" ON "payments"("dueDate");

-- ============================================================
-- SECTION 3: PaymentReminders — who was chased, and when
-- ============================================================
CREATE TABLE "payment_reminders" (
    "id" TEXT NOT NULL,
    "paymentId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "channel" TEXT NOT NULL DEFAULT 'WHATSAPP',
    "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payment_reminders_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "payment_reminders_paymentId_sentAt_idx" ON "payment_reminders"("paymentId", "sentAt");

ALTER TABLE "payment_reminders" ADD CONSTRAINT "payment_reminders_paymentId_fkey"
    FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payment_reminders" ADD CONSTRAINT "payment_reminders_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
